#ifndef PROOFSERVICE_WEIGHING_SCALE_GLOBAL_H
#define PROOFSERVICE_WEIGHING_SCALE_GLOBAL_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(proofServiceWeighingScaleLog)

#endif // PROOFSERVICE_WEIGHING_SCALE_GLOBAL_H
